# Generated by Django 3.2.4 on 2021-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHireApp', '0002_auto_20210909_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('1', 'Single Choice')], max_length=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Single Choice')], max_length=10, null=True),
        ),
    ]
