# Generated by Django 2.2.24 on 2021-06-24 11:03

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_title', models.CharField(max_length=100)),
                ('course_slug', models.SlugField(blank=True, null=True)),
                ('enrolled_students', models.IntegerField(default=100)),
                ('course_price', models.IntegerField(default=100)),
                ('course_image', models.ImageField(upload_to='courses')),
                ('course_upload_on', models.CharField(choices=[('Vimeo', 'Vimeo'), ('Youtube', 'Youtube')], default='Vimeo', max_length=100)),
                ('discount_price', models.IntegerField(default=0)),
                ('course_description', froala_editor.fields.FroalaField()),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.FileField(upload_to='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseChapters',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter_title', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter_type', models.CharField(choices=[('Lesson', 'Lesson'), ('Code', 'Code'), ('MCQ', 'MCQ')], max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDiscount',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0)),
                ('to_be_applied', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_link', models.URLField()),
                ('lesson_title', models.CharField(blank=True, max_length=100, null=True)),
                ('can_watch', models.BooleanField(default=False)),
                ('video_duration', models.CharField(max_length=30)),
                ('course_chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='courses.CourseChapters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory'),
        ),
    ]
