# Generated by Django 3.2.4 on 2021-06-30 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.FileField(upload_to='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDiscount',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0)),
                ('to_be_applied', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_title', models.CharField(max_length=100)),
                ('subject_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('order', models.IntegerField()),
                ('subject_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory')),
            ],
            options={
                'verbose_name_plural': 'Course Subject',
                'db_table': 'course_subject',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectChapters',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter_title', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='courses.subject')),
            ],
            options={
                'verbose_name_plural': 'Subject chapters',
                'db_table': 'course_chapters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_title', models.CharField(blank=True, max_length=100, null=True)),
                ('lesson_type', models.CharField(choices=[('Video', 'Video'), ('Document', 'Document'), ('Video + Document', 'Video + Document')], max_length=100)),
                ('video_uploaded_on', models.CharField(blank=True, choices=[('Vimeo', 'Vimeo'), ('Youtube', 'Youtube')], max_length=100, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_free', models.BooleanField(default=False)),
                ('subject_chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='courses.subjectchapters')),
            ],
            options={
                'verbose_name_plural': 'Lesson chapters',
                'db_table': 'lesson_chapters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_bundle_name', models.CharField(max_length=100)),
                ('course_bundle_description', models.TextField()),
                ('course_bundle_image', models.ImageField(upload_to='courses')),
                ('course_bundle_price', models.IntegerField()),
                ('course_bundle_discount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course_validity', models.DateField()),
                ('course_bundle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory')),
                ('courses', models.ManyToManyField(to='courses.Subject')),
            ],
            options={
                'verbose_name_plural': 'Course Bundle',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
    ]
