# Generated by Django 3.2.4 on 2021-06-28 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBundle',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_bundle_name', models.CharField(max_length=100)),
                ('course_bundle_description', models.CharField(max_length=100)),
                ('course_bundle_price', models.IntegerField()),
                ('course_bundle_discount', models.IntegerField(default=0)),
                ('course_bundle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory')),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
