# Generated by Django 3.2.4 on 2021-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
