# Generated by Django 3.2.4 on 2021-06-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_slug',
        ),
    ]
