# Generated by Django 3.2.4 on 2021-06-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursebundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='course_bundle_image',
            field=models.ImageField(default='', upload_to='courses'),
            preserve_default=False,
        ),
    ]
