# Generated by Django 3.2.4 on 2021-07-10 05:43

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_subject_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_bundle_description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
