# Generated by Django 3.2.4 on 2021-06-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_subject_subject_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='subjects',
        ),
    ]
