# Generated by Django 3.2.4 on 2021-06-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursebundle_course_bundle_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Course Subject'},
        ),
        migrations.AlterModelOptions(
            name='coursebundle',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Course Bundle'},
        ),
        migrations.AlterModelOptions(
            name='coursechapters',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Subject chapters'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Lesson chapters'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='course_subject',
        ),
        migrations.AlterModelTable(
            name='coursebundle',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursechapters',
            table='course_chapters',
        ),
        migrations.AlterModelTable(
            name='lessons',
            table='lesson_chapters',
        ),
    ]
