# Generated by Django 3.2.4 on 2021-07-12 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_bundle_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_stream_link', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
