# Generated by Django 3.2.4 on 2021-07-18 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursecategory_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_title', models.CharField(max_length=100)),
                ('package_description', froala_editor.fields.FroalaField()),
                ('package_image', models.ImageField(upload_to='courses')),
                ('actual_price', models.IntegerField()),
                ('selling_price', models.IntegerField(default=0)),
                ('sell_from', models.DateField()),
                ('sell_till', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('course_validity', models.DateField()),
                ('web_image', models.ImageField(upload_to='course_package')),
                ('mobile_image', models.ImageField(upload_to='course_package')),
            ],
            options={
                'verbose_name_plural': 'Course Package',
                'db_table': 'course_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_bundle_category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='subject_chapters',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_category',
        ),
        migrations.RemoveField(
            model_name='subjectchapters',
            name='subject',
        ),
        migrations.AddField(
            model_name='lessons',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='publish_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 11, 10, 28, 674614, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
    ]
