# Generated by Django 3.2.4 on 2021-07-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_subjectchapters_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='subject_chapters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subjectchapters'),
        ),
    ]
