# Generated by Django 3.2.4 on 2021-07-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210721_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='subject_chapters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lessons', to='courses.subjectchapters'),
        ),
    ]
