# Generated by Django 3.2.4 on 2021-07-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_lessons_subject_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='course_chapters',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='course_lessons',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='course_subjects',
            field=models.TextField(default='[]'),
        ),
    ]
