# Generated by Django 3.2.4 on 2021-07-23 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210723_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackageChapters',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoursePackageSubjects',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacakge_subjects', to='courses.coursepackage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoursePackageLessons',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField(default=1)),
                ('course_package_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacakge_subject_chapters_lessons', to='courses.coursepackagechapters')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coursepackagechapters',
            name='course_package_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacakge_subject_chapters', to='courses.coursepackagesubjects'),
        ),
        migrations.AddField(
            model_name='coursepackagechapters',
            name='subject_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subjectchapters'),
        ),
    ]
