# Generated by Django 3.2.4 on 2021-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lessons_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepackage',
            name='course_chapters',
        ),
        migrations.RemoveField(
            model_name='coursepackage',
            name='course_lessons',
        ),
        migrations.RemoveField(
            model_name='coursepackage',
            name='course_package_info',
        ),
        migrations.RemoveField(
            model_name='coursepackage',
            name='course_subjects',
        ),
        migrations.RemoveField(
            model_name='coursepackage',
            name='package_image',
        ),
        migrations.RemoveField(
            model_name='coursepackage',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='sell_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='sell_till',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
