# Generated by Django 3.2.4 on 2021-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_subjectchapters_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_file', models.FileField(upload_to='documents')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_uploaded_on', models.CharField(blank=True, choices=[('Vimeo', 'Vimeo'), ('Youtube', 'Youtube')], max_length=100, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='video_uploaded_on',
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Document', 'Document'), ('Quiz', 'Quiz')], default='Video', max_length=100),
        ),
    ]
