# Generated by Django 3.2.4 on 2021-08-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_lessons_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.document'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.video'),
        ),
    ]
