# Generated by Django 3.2.4 on 2021-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20210801_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Document', 'Document'), ('Video + Document', 'Video + Document'), ('Quiz', 'Quiz')], default='Video', max_length=100),
        ),
    ]
