# Generated by Django 3.2.4 on 2021-09-01 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_lessons_lesson_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoLive',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_name', models.CharField(max_length=100)),
                ('live_url', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='live')),
                ('live_date', models.DateTimeField()),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subjectchapters')),
                ('course_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursepackage')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
