# Generated by Django 3.2.4 on 2021-09-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_golive'),
    ]

    operations = [
        migrations.AddField(
            model_name='golive',
            name='live_time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golive',
            name='live_date',
            field=models.CharField(max_length=100),
        ),
    ]
