# Generated by Django 3.2.4 on 2021-09-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20210907_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golive',
            name='course_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='courses.coursepackage'),
        ),
    ]
