# Generated by Django 3.2.4 on 2021-09-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_golive_course_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golive',
            name='live_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
