# Generated by Django 3.2.4 on 2021-09-14 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20210915_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupoun',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('coupon_discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='courses.CoursePackage')),
            ],
            options={
                'verbose_name_plural': 'Coupon ',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
