# Generated by Django 3.2.4 on 2021-09-17 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_lessons_subject_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='chapter',
        ),
        migrations.AddField(
            model_name='lessons',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='subject_chapters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lessons', to='courses.subjectchapters'),
        ),
    ]
