# Generated by Django 3.2.4 on 2021-09-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20210917_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='subject_chapters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_lessons', to='courses.subjectchapters'),
        ),
    ]
