# Generated by Django 3.2.4 on 2021-09-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20210917_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='subject_chapters',
            new_name='chapter',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='subject',
        ),
    ]
