# Generated by Django 3.2.4 on 2021-09-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20210917_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepackagelessons',
            name='sequence',
        ),
    ]
