# Generated by Django 3.2.4 on 2021-09-18 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_remove_coursepackagelessons_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golive',
            name='live_date',
        ),
        migrations.RemoveField(
            model_name='golive',
            name='live_time',
        ),
        migrations.AddField(
            model_name='golive',
            name='live_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='golive',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subjectchapters'),
        ),
        migrations.AlterField(
            model_name='golive',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
