# Generated by Django 3.2.4 on 2021-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20210918_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepackage',
            name='course_validity',
        ),
        migrations.RemoveField(
            model_name='coursepackage',
            name='sell_from',
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='package_type',
            field=models.CharField(choices=[('Fixed Date', 'Fixed Date'), ('Subscription', 'Subscrption')], default='Fixed Date', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='actual_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='mobile_image',
            field=models.ImageField(upload_to='course_package'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='package_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='sell_till',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='selling_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='web_image',
            field=models.ImageField(upload_to='course_package'),
        ),
    ]
