# Generated by Django 3.2.4 on 2021-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_coursepackagelessons_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='golive',
            name='live_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
