# Generated by Django 3.2.4 on 2021-09-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_golive_live_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepackage',
            old_name='sell_till',
            new_name='sell_till_date',
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='subscription_type',
            field=models.CharField(choices=[('Fixed Date', 'Fixed Date'), ('Subscription', 'Subscrption')], default='Fixed Date', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='package_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Test', 'Test')], default='Video', max_length=100),
        ),
    ]
