# Generated by Django 3.2.4 on 2021-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20210919_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupoun',
            name='coupon_discount_type',
        ),
        migrations.RemoveField(
            model_name='coupoun',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='coupoun',
            name='start_date',
        ),
        migrations.AddField(
            model_name='coupoun',
            name='coupon_validity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupoun',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Discount', 'Fixed Discount'), ('Percentage Discount', 'Percentage Discount')], default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupoun',
            name='per_user_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='coupoun',
            name='total_usage_limit',
            field=models.IntegerField(default=-1),
        ),
    ]
