# Generated by Django 3.2.4 on 2021-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20210921_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='golive',
            name='is_live_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='golive',
            name='is_live_started',
            field=models.BooleanField(default=False),
        ),
    ]
