# Generated by Django 3.2.4 on 2021-09-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20210925_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupoun',
            name='applied_total_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupoun',
            name='applied_user_limit',
            field=models.IntegerField(default=0),
        ),
    ]
