# Generated by Django 3.2.4 on 2021-10-01 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20210927_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_image', models.ImageField(upload_to='sliders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
