# Generated by Django 3.2.4 on 2021-10-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
