# Generated by Django 3.2.4 on 2021-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_slider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='golive',
            name='courses',
            field=models.ManyToManyField(to='courses.CoursePackage'),
        ),
    ]
