# Generated by Django 3.2.4 on 2021-10-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_golive_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golive',
            name='course_package',
        ),
    ]
