# Generated by Django 3.2.4 on 2021-10-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_remove_golive_course_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golive',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.CoursePackage'),
        ),
    ]
