# Generated by Django 3.2.4 on 2021-10-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_golive_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golive',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.CoursePackage'),
        ),
    ]
