# Generated by Django 3.2.4 on 2021-10-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_video_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='download_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
