# Generated by Django 3.2.4 on 2021-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.TextField(default='{}'),
        ),
    ]
