# Generated by Django 3.2.4 on 2021-08-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payement_id',
            new_name='payement_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_signature',
        ),
    ]
