# Generated by Django 3.2.4 on 2021-08-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0022_alter_lessons_lesson_type'),
        ('orders', '0005_alter_order_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('student', 'course')},
        ),
    ]
