# Generated by Django 3.2.4 on 2021-09-27 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20210927_1314'),
        ('orders', '0007_alter_order_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coupoun'),
        ),
    ]
