# Generated by Django 3.2.4 on 2021-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
