# Generated by Django 3.2.4 on 2021-06-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-uid'], 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
