# Generated by Django 3.2.4 on 2021-09-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_phone_verified',
            field=models.BooleanField(default=True),
        ),
    ]
