# Generated by Django 3.2.4 on 2021-11-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210927_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
