# Generated by Django 3.2.4 on 2021-08-28 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLogs',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notfication_title', models.CharField(max_length=100)),
                ('notification_content', models.TextField()),
                ('notification_image', models.ImageField(blank=True, null=True, upload_to='notifications')),
                ('logs', models.TextField(default='{}')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
